version: '3.7'
services:
  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "4306:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    build: .
    # command: >
    #   bash -c "
    #     yarn install --check-files &&
    #     rm -f tmp/pids/server.pid &&
    #     bundle install --quiet &&
    #     bundle exec rails db:migrate
    #   "
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - mysql
    # working_dir: "/app"