version: 2.1

executors:
  default:
    working_directory: ~/rails_vue_TODOlist
    docker:
      - image: circleci/ruby:2.6.1-node
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

      - image: circleci/mysql:8.0.16
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
          MYSQL_DATABASE: rails_vue_TODOlist_test

commands:
  save_code_cache:
    steps:
      - save_cache:
          key: v1-code-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths: ~/rails_vue_TODOlist

  restore_code_cache:
    steps:
      - restore_cache:
          key: v1-code-cache-{{ .Environment.CIRCLE_SHA1 }}

  save_gem_cache:
    steps:
      - save_cache:
          key: v1-gem-cache-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle

  restore_gem_cache:
    steps:
      - restore_cache:
          key: v1-gem-cache-{{ checksum "Gemfile.lock" }}

jobs:
  fetch_source_code:
    executor: default
    steps:
      - checkout
      - save_code_cache

  bundle_dependencies:
    executor: default
    steps:
      - checkout
      - restore_code_cache
      - restore_gem_cache
      - run:
          name: Bundle Install Dependencies
          command: |
            gem install bundler -v 2.0.1
            bundle install
      - save_gem_cache

  rubocop:
    executor: default
    steps:
      - checkout
      - restore_code_cache
      - restore_gem_cache
      - run:
          name: Execute rubocop
          command: |
            gem install bundler -v 2.0.1
            bundle exec rubocop

  rspec:
    executor: default
    steps:
      - checkout
      - restore_code_cache
      - restore_gem_cache
      - run:
          name: Watting stand up database
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Database setup
          command: |
            mv ./config/database.yml.ci  ./config/database.yml
      - run:
          name: Testing DB migration and seed
          command: |
            gem install bundler -v 2.0.1
            bundle exec rails db:create db:migrate db:seed db:drop
      - run:
          name: Run RSpec
          command: |
            mkdir /tmp/test-results
            mkdir -p ~/rspec
            bundle exec rails db:create db:migrate
            gem install bundler -v 2.0.1
            bundle exec rspec
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: /tmp/test-results
          destination: build

workflows:
  build:
    jobs:
      - fetch_source_code
      - bundle_dependencies:
          requires:
            - fetch_source_code
      - rubocop:
          requires:
            - bundle_dependencies
      - rspec:
          requires:
            - bundle_dependencies